### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by fire** [tony612/grpc-elixir#1]
Need any help?

**Comment by tony612** [comment]
What kind of help?

**Comment by fire** [comment]
I could try writing tests or adding typespecs.

**Comment by fire** [comment]
I also know how to create a travis setup.

**Comment by tony612** [comment]
@fire Maybe not now. I plan to do these things, whose priority is low, when the code is more stable and more functions are added. Thanks you all the same!

**Comment by tony612** [comment]
@fire But Travis maybe a good idea.
