### ISSUE TITLE
Middlewares support

### ISSUE THREAD

**Issue by jhchabran** [tony612/grpc-elixir#12]
Hi, thanks for grpc-elixir, it's enabling my company to move toward Elixir faster :] 

There's a bunch of features in [grpc-go](https://github.com/grpc/grpc-go) that we're relying upon that would greatly benefit grpc-elixir. 

One of those is [support for interceptors](https://github.com/grpc/grpc-go/blob/9f9c1906922195abfc35b3791d0aa106af88b6ab/interceptor.go), which basically enable to write middlewares for things such as _logging_,  _metrics reporting_ and _retrying_. 

While such a feature can be implemented on top of the generated code, it makes it difficult to write certain middlewares with only let's say `say_hello(request, _stream)`. 

So I was looking at the code and thinking that it could be implemented (in broad terms) like that: 

```elixir
# Server-side
defmodule Helloworld.Greeter.Server do
  use GRPC.Server, service: Helloworld.Greeter.Service, middlewares: [m1,m2]

  def say_hello(request, _stream) do
    Helloworld.HelloReply.new(message: "Hello #{request.name}")
  end
end

# Client-side
{:ok, channel} = GRPC.Stub.connect("localhost:50051")
reply = 
  channel 
  |> Helloworld.Greeter.Stub.say_hello(Helloworld.HelloRequest.new(name: "grpc-elixir", middlewares: [m1, m2])
```

A middleware being defined broadly as following: 

```elixir
# Server-side
defmodule Helloworld.Greeter.LoggingServerMiddleware do
  def call(service_mod, stream, {_, {req_mod, req_stream}, {res_mod, res_stream}} = _rpc, func_name, next_mod) do
    Logger.info(...)
    next.call(service_mod, stream, rpc), func_name, next_mod) 
    # or perform the request with send_request/5 to short circuit the chain 
  end
end

# Client-side
defmodule Helloworld.Greeter.LoggingClientMiddleware do
  @spec call(atom, tuple, String.t, GRPC.Channel, struct | nil, keyword, atom) :: any
  def call(service_mod, rpc, path, channel, request, opts, next_mod) do
     Logger.info(...)
     next.call(service_mod, rpc, path, channel, request, opts, next_mod)
  end
end
```

Tbh, something like [Plug](https://github.com/elixir-lang/plug/blob/master/lib/plug/builder.ex) would be nicer but I'd rather go for the straightforward implementation first. 

What do you think about such an approach? 

I think I can find time at work to implement this but I'd rather talk with you about it first :)

**Comment by tony612** [comment]
It's an interesting idea so that we can have some cool features like monitoring, logging and so on. It's already on my wishlist but I'm still working on the protobuf thing. Your solution looks fine for me. You can try to implement it and please ping me if you have problems 😬

**Comment by jhchabran** [comment]
Ack, will get in touch then :] 

Yeah, I've seen you're working on replacing the generating part by [something much cleaner](https://github.com/tony612/protobuf-elixir), that's great :]

**Comment by vonmixer** [comment]
@jhchabran What's the status on this? I can give it a go.

**Comment by jhchabran** [comment]
@vonmixer Damn this issue had been opened for so long, sorry for not giving news. 

I've resumed work on this during the past week. So far got working code for middlewares on server side, both unary and streaming. I'll push my code beginning of next week, I need to clean stuff and write some tests.

**Comment by vonmixer** [comment]
Sounds great thanks!

**Comment by kodburn** [comment]
Hi, @jhchabran Do you already use grpc-elixir in production? 
We are migrating the stack to kubernetes, and we're going to use grpc as the microservice communication tool(for now we use rabbitmq). We have a couple of elixir otp apps, and I'm not sure how prod ready this library is.

I'd be really glad to start contributing to this project as soon as I get more familiar with otp quirks.

**Comment by jhchabran** [comment]
Hi @kodburn. No we don't yet, while we use GRPC within Go services in our services, our existing Elixir services not interacting much with those services so we don't need it right now. But that's definitively something we want to do and that's what triggered the need for middlewares and I'll be have some time to return finishing this PR ^^ 

Though, regarding production readiness, I believe that @tony612 can provide a much more relevant answer 😄 .

**Comment by tony612** [comment]
The performance of server side is OK for most situations, but the client side is not good enough. You can refer to the benchmark code https://github.com/darkofabijan/grpc-stress-test and the result https://semaphoreci.com/darkofabijan/grpc-stress-test/branches/master/builds/49 . The API is not very stable now. But if you only use unary calls and don't use too much custom options, you can try it in production :)

**Comment by tony612** [comment]
btw, I'm looking into how to improve the client side performance recently, try to make the APIs more stable and add more docs. Then it'll be a better time to use it in production, I think. 😁

**Comment by bjuretic** [comment]
@jhchabran Did you think about passing some context/meta struct around between the middlewares? That is pretty standard, otherwise there is no way to push data forward in the chain. For example authentication is one middleware, and it pushes the user_id which is retrieved to the next middleware, and eventually to the actual business logic / server method.

@tony612 What I just wrote would need some kind of support so that the server method can retrieve the middleware-generated data. Something like the :assigns in the `plug`.

**Comment by jhchabran** [comment]
@bjuretic Yeah it's pretty standard (I've wrote my share of Go GRPC middlewares and I've used them ^^). I haven't put a lot of thoughts into this lately, but I'll be doing another pass soon and I think this could easily added.
