### ISSUE TITLE
Any news on the Cowboy branch?

### ISSUE THREAD

**Issue by cafreeman** [tony612/grpc-elixir#13]
I'm looking to incorporate this into a Phoenix app at work, but `mix` complains about a conflict on the `cowboy` dependency because this packages uses a fork of the official lib.

Are there plans to move to using the official version of `cowboy` in the near future?

**Comment by tony612** [comment]
I'm still waiting for https://github.com/ninenines/cowboy/pull/1020 to be merged.

And there will still be a conflict even if I use official version of cowboy because cowboy2.0 is not published on hex. So we have to wait for that and that Phoenix has support for cowboy2.0.
