### ISSUE TITLE
Disabling of lager for library users

### ISSUE THREAD

**Issue by svetob** [tony612/grpc-elixir#14]
Have been using this library for the last few weeks and really liking it - simple and quick to get started. Kudos! :)

My only major problem so far, is that the grpc-elixir imports `lager`, which seems to take over the logging stack (as in, make itself the default logging library) with no obvious way of turning it off. This could unfortunately be a blocker for using the lib for me. Obviously, the choice of logging stack should be the choice of the user. 

I am not sure what the best way to accomplish this would be. I don't see any lager configuration option to disable it, and it seems to be a hard dependency in chatterbox. If we can find an easy way to do this on the user end, perhaps we could add it to the readme?

**Comment by tony612** [comment]
Yes, chatterbox dependents on lager. Even if I remove lager from `mix.exs`, chatterbox will start lager. I didn't see a easy way to remove lager. I'll close this issue. If you find a way, please open an issue or send a PR.
