### ISSUE TITLE
Stress testing Elixir <=> Elixir and Ruby <=> Elixir communication

### ISSUE THREAD

**Issue by darkofabijan** [tony612/grpc-elixir#22]
If calls between Ruby and Elixir are performed in any combination by hand with manually triggering client calls from shell things work without any issues. Not sure if relevant but just a note that in this case client process is short lived - one rpc call per process.

I was browsing tests for Ruby implementation and noticed that they have [stress tests](https://github.com/grpc/grpc/tree/master/src/ruby/stress) so I wanted to try something like that. I just put a loop around client in [Ruby](https://github.com/darkofabijan/grpc-stress-test/blob/master/grpc/examples/ruby/greeter_client.rb#L13-L17) and [Elixir](https://github.com/darkofabijan/grpc-stress-test/blob/master/grpc-elixir/examples/helloworld/priv/client.exs#L2-L6) to perform 100K calls in helloworld example. This is far from the proper stress test, no concurrency in client calls is introduced and probably some other things are missing. Just first step.

Here is a short report on how things work:

* 💥  Elixir client => Elixir server can survive around 3K calls before crashing
* ✅  Ruby client => Ruby server can survive 100K calls without any issues
* 💥  Elixir client => Ruby server can survive between 1 to 3 calls. If timeout between calls is introduced it can survive a bit longer, maybe 10 calls.
* 💥  Ruby client => Elixir server can survive around 6K calls

Results with logs and exceptions can be seen here – https://semaphoreci.com/darkofabijan/grpc-stress-test/branches/master/builds/17
Code is in – https://github.com/darkofabijan/grpc-stress-test/

Also, these stress tests are not systematically organized and it's not possible to easily test changes. I took a shortcut and just committed everything in a single repo to test out this approach. I can think about introducing a more systematic approach that can scale and follow in CI automatically. This is also probably good groundwork for benchmarking.

P.S.
grpc-elixir is using this version of chatterbox - https://github.com/joedevivo/chatterbox/pull/114

**Comment by tony612** [comment]
👍  Good job! Though the result for Elixir is not good, with this we can improve it. Thanks again for your work!

**Comment by tony612** [comment]
@darkofabijan There're two problems with your tests:
1. The server should be started with `MIX_ENV=prod`. Could you change the configuration of semaphoreci?
2. The client script is run using `mix run priv/client.exs`, which should be slow and should not be used in production env.

**Comment by darkofabijan** [comment]
@tony612 

1. Just added `MIX_ENV=prod` and I also added you as a collaborator on the project.
2. Moving it to a mix task should be fine, right?

**Comment by tony612** [comment]
@darkofabijan Let's try mix task first :)

**Comment by darkofabijan** [comment]
Just a note that this [build](https://semaphoreci.com/darkofabijan/grpc-stress-test/branches/master/builds/25) is more realistically reflecting situation from the original description.

**Comment by darkofabijan** [comment]
@tony612 I spend some time debugging `Elixir client => Ruby server` I got some insight, but my understanding still too shallow to make more progress.

On third rpc call `END_STREAM` never arrives. The question is if headers and body are successfully sent and then received by Ruby side.

```
1
Got END_STREAM
%Helloworld.HelloReply{message: "Hello 1"}
2
Got END_STREAM
%Helloworld.HelloReply{message: "Hello 2"}
3
RESSS
:not_ready
** (GRPC.TimeoutError) 4: deadline exceeded
    (grpc) lib/grpc/adapter/chatterbox/client.ex:78: GRPC.Adapter.Chatterbox.Client.recv_end/2
    (grpc) lib/grpc/stub.ex:70: GRPC.Stub.send_request/5
    priv/client.exs:4: anonymous fn/2 in :elixir_compiler_4.__FILE__/1
    (elixir) lib/enum.ex:651: anonymous fn/3 in Enum.each/2
    (elixir) lib/enum.ex:1785: Enum.reduce_range_inc/4
    (elixir) lib/enum.ex:1760: Enum.each/2
```

You can check where I was digging ⛏ here:
- https://github.com/darkofabijan/grpc-stress-test/pull/1/files
- https://semaphoreci.com/darkofabijan/grpc-stress-test/branches/rb-ex-debugging/builds/2

---

For `Elixir server` context, I think it's something connected with a timeout or something similar very predictable on server (maybe cowboy) side. 

`Ruby client => Elixir server` dies after 6K calls or after ~30 seconds.
`Elixir client => Elixir server` dies after 1.3K calls or after ~60 seconds.

This experiment also has very similar, predictable behavior – https://github.com/darkofabijan/grpc-elixir/pull/1/files. To see just run `mix test` and wait for like 70 seconds.

**Comment by tony612** [comment]
I tried with Elixir client -> Go server, it works normally(more than 10,000 requests, then I kill it). So I guess it's because chatterbox can't handle the Ruby implementation normally.

**Comment by darkofabijan** [comment]
Good to know! Let me try to add those combinators to `stress` repo also. Go <=> Ruby and Go <=> Elixir.  It should further narrow down the area where 🐞 could be.

**Comment by tony612** [comment]
@darkofabijan 👍  I'm looking into the Elixir client -> Ruby server problem. From the result of wireshark, after the last DATA frame is sent by the client, no frame is sent by the server.

**Comment by tony612** [comment]
@darkofabijan The elixir client bug is fixed, though the speed is still a little slow. See https://github.com/joedevivo/chatterbox/pull/115 for details.

**Comment by tony612** [comment]
I updated cowboy of grpc-elixir to latest, it seems more stable now. As https://semaphoreci.com/darkofabijan/grpc-stress-test/branches/master/builds/37 shows,
- Go client => Elixir server can finish now
- Ruby client => Elixir server can reach to 95979 in 6 minutes. Then it seems timeout

**Comment by darkofabijan** [comment]
@tony612 sounds great! :) 💜 

Let me think how we can help with testing this further 🚀

**Comment by jaigouk** [comment]
@tony612 thanks for the hard work. @darkofabijan i am also playing with ruby!!

**Comment by darkofabijan** [comment]
The main problem in this issue is solved by @tony612  with [PR on chatterbox](https://github.com/joedevivo/chatterbox/pull/115). Thanks a ton! :)

We also got some additional insight into stability and performance of Elixir grpc client and server.

Let me try to sum up what [build 37](https://semaphoreci.com/darkofabijan/grpc-stress-test/branches/master/builds/37) that @tony612 shared tells us and share some of the ideas that we have for next steps.

### Stats

| Client             | Server            | Duration for 100K calls   |    Status    |
| ------------- | ------------- |-------------------------|-----------|
| Go                  | Go                  |    3:42                              |         ✅      |
| Ruby              | Go                  |    6:08                              |         ✅      |
| Elixir              | Go                  |    10:00 (timeout)             |         💥 (12K calls)      |
| Go                 | Elixir               |    5:22                               |         ✅      |
| Ruby             | Elixir               |    6:27                               |         💣  (96K calls)      |
| Elixir              | Elixir               |    10:00 (timeout)             |         💥 (13K calls)      |
| Go                 | Ruby               |    4:19                               |         ✅      |
| Ruby             | Ruby               |    6:18                               |         ✅      |
| Elixir              | Ruby               |    10:00 (timeout)            |         💥 (13K calls)      |

---

1. `Ruby client => Elixir server` combination is a special case. It get's very close to 100k, sometimes even 99K but then dies. Almost always around 6 minutes.
2. `Elixir client => Any server` can execute around 13K calls in 10 minutes. There is a serious performance bottleneck here. Since this is our (@renderedtext) primary use-case for our @semaphoreci during next month or so we plan to first focus on further benchmarking of this and hopefully also fixing it. This seems to be the simplest part of the code so we hope that we will be able to contribute in this area relatively easy. Of course, we will share once we have more news :)

@tony612 what do you think? Should we close this issue? Or do we want to wait until chatterbox PRs related to this are merged?

- https://github.com/joedevivo/chatterbox/pull/114
- https://github.com/joedevivo/chatterbox/pull/115

**Comment by darkofabijan** [comment]
Just a note that we will be experimenting with `Elixir client => Ruby server` here – https://github.com/renderedtext/grpc-stress 🕺 

Once we learn more we will open PR for some stress/e2e tests. Who know maybe even with some benchmarks :)

**Comment by tony612** [comment]
Cool. I think we can close this issue. We can discuss the client problem in
a new issue if you want. Please let me know if I can do something for this
client problem :)
