### ISSUE TITLE
Mini question

### ISSUE THREAD

**Issue by AleksandarFilipov** [tony612/grpc-elixir#25]
Hello tony,

i'm eager to test your code but i'm having trouble getting started it seems like the mix task grpc.gen has been removed which is referenced from the docs and examples. I'm having trouble finding what it has been replaced with. Would apprechiate some pointers in the right direction

**Comment by tony612** [comment]
You can use https://github.com/tony612/protobuf-elixir to generate code. I'll update the doc in this lib later.

**Comment by AleksandarFilipov** [comment]
Thank you for updating! About to take your work for a ride :)

**Comment by tony612** [comment]
@AleksandarFilipov Please ping me if you have any problem 😄

**Comment by AleksandarFilipov** [comment]
I'm back and got some samples running, keep up the good work!

**Comment by AleksandarFilipov** [comment]
So I'm struggling a bit understanding how to make server request asynch. If managed to connect to a genserver by sending the stream to it and blocking the calling pid. Once the stream is finished I let go of the block (lock) and the stream terminates. This works well, but I've got a feeling that it's not how intended it to work. Using this approach it's unclear to me how I would handle client disconnect. I assume there are some callbacks I've missed such as streamdisconnect. Please point me to an example if there os one which I've missed.

**Comment by tony612** [comment]
I'm not sure if I fully understand your problem. But if the client has a problem after sending the request. The client should be able to reconnect and you can still use that connection. If you find there're unexpected problems, please report.

**Comment by AleksandarFilipov** [comment]
Ok, one question at a time 😀. I'm on the serverside with you library. A client connects and a stream is returned. I think of it as a subscription (a genserver writes to the stream in my implementation). Once the client is satisfied with its subscription it disconnects. Question: how do I know that the client is disconnected, where do I put the server side code to stop feeding the stream with data? (The stream is fed from my genserver)

**Comment by tony612** [comment]
@AleksandarFilipov There's no support for that now. But maybe we can get the info from cowboy. I'll look into cowboy's code to see how to do that.

**Comment by AleksandarFilipov** [comment]
Sounds great. Now I know I haven't missed something obvious. I'll have look around and I'll try to understand how it works, and potentially be of some help.

**Comment by AleksandarFilipov** [comment]
A few months has passed and here are my findings :). This really isn't an issue.

Well if the client disconnects abruptly cowboy will 
```
exit(Pid, shutdown) 
```
which means that otp also will bring down any linked process (since the reason isn't normal). In my scenario  this is neatly hadled by adding 
```
Process.flag(:trap_exit, true)
```
to my genserver, which in turn will get a callback to terminate, giving me a chance to clean up any ongoing leftovers.

My remaining consern is that i have trouble writing testcode for the thing since the terminate is only called once the testcode is terminate, but thats a diffrent story
