### ISSUE TITLE
HTTP2 Content-Type Option

### ISSUE THREAD

**Issue by cjab** [tony612/grpc-elixir#26]
Hi there, I just came across grpc-elixir the other day and decided to see if I could build a Google Datastore client from Google's IDL files. It looks like auth isn't completely supported yet or at least the type of auth needed for datastore (I'm still really fuzzy on how datastore auth works). In the meantime I'm testing against Google's local datastore emulator.

The first snag I hit is that datastore emulator requires the `content-type` header to be `application/grpc` instead of `application/grpc+proto`. After changing the header it works! But it doesn't look like there's a way to set the content-type header through options.  On the one hand it looks like datastore emulator may not be completely following spec, but on the other hand this type of problem may be common. Would you be against a PR that added either a content-type or more generically headers to options on Stub.connect?

**Comment by tony612** [comment]
This is supported now, like `Helloworld.Greeter.Stub.say_hello(channel, req, content_type: "")`
