### ISSUE TITLE
Multiple services on same port

### ISSUE THREAD

**Issue by cwertyar** [tony612/grpc-elixir#33]
Hello!

I'm sorry if this is obvious and I just missed it, I'm pretty new to elixir. 
Is it possible to have multiple services on the same port as with other GRPC implementations?

**Comment by tony612** [comment]
It's supported :)

**Comment by cwertyar** [comment]
That's good to hear!

Could you maybe give a short example @tony612 as no current example in this repo shows it? Thank you!

**Comment by tony612** [comment]
You can see the examples in `examples`. You should be able to call multiple services with one channel like
```
# the helloworld example
{:ok, channel} = GRPC.Stub.connect("localhost:50051")
reply = channel |> Helloworld.Greeter.Stub.say_hello(Helloworld.HelloRequest.new(name: "grpc-elixir"))
reply = channel |> Another.Service.foo(Helloworld.HelloRequest.new(name: "grpc-elixir"))
```
Try something like this. If it doesn't work, please tell me.

**Comment by cwertyar** [comment]
Thank you for the sample :) this seems to work with my go server.
What I'm struggling with is the server side as I'm always getting an error when registering the GRPC supervisor a second time with another service using this code:

```
# In the start function of your Application
def start(_type, _args) do
  children = [
    # ...
    supervisor(GRPC.Server.Supervisor, [{Helloworld.Greeter.Server, 50051}]),
    supervisor(GRPC.Server.Supervisor, [{Other.Service.Greeter.Server, 50051}]),
  ]

  opts = [strategy: :one_for_one, name: MyApp]
  Supervisor.start_link(children, opts)
end
```

**Comment by tony612** [comment]
This is not supported. But I can add this feature these days.

**Comment by cwertyar** [comment]
That would be awesome. I want to port over a part of our GRPC stuff from go to elixir and our whole setup depends on multiple services being available from the same port.

**Comment by tony612** [comment]
Fixed. You can use a server list in child_spec like
```
children = [
    # ...
    supervisor(GRPC.Server.Supervisor, [{[Helloworld.Greeter.Server, Other.Service.Greeter.Server], 50051}])
  ]
```
Please update grpc with `mix deps.update grpc`
