### ISSUE TITLE
can't keepalive

### ISSUE THREAD

**Issue by yizhiren** [tony612/grpc-elixir#4]
connect between client and server will broken after a while, 

```



defmodule REPLTalk do

	def repltalk(channel) do

		questionAsking = IO.gets "> "
		if (byte_size(questionAsking) <= 1) do
			repltalk(channel)
		else
			#IO.puts("thinking...")
			reply = channel |> Talker.Talker.Stub.ask_question(Talker.Ask.new(question: questionAsking))
			IO.inspect reply.answer
			repltalk(channel)
		end
	end
end

GRPC.Server.start(Talker.Talker.Server, "localhost:50051", insecure: true)
{:ok, channel} = GRPC.Stub.connect("localhost:50051", insecure: true)
REPLTalk.repltalk(channel)

```

** (exit) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.321.0>, {:new_stream, #PID<0.71.0>})
    ** (EXIT) no process
    (stdlib) gen_fsm.erl:249: :gen_fsm.sync_send_all_state_event/2
    (grpc) lib/grpc/adapter/chatterbox/client.ex:37: GRPC.Adapter.Chatterbox.Client.send_header/2
    (grpc) lib/grpc/adapter/chatterbox/client.ex:28: GRPC.Adapter.Chatterbox.Client.send_request/3
    (grpc) lib/grpc/adapter/chatterbox/client.ex:21: GRPC.Adapter.Chatterbox.Client.unary/3
    (grpc) lib/grpc/stub.ex:70: GRPC.Stub.send_request/5
    run.exs:12: REPLTalk.repltalk/1

16:50:19.230 [error] GenServer GRPC.Adapter.Cowboy.ServerSup terminating
** (stop) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.321.0>, {:new_stream, #PID<0.71.0>})
    ** (EXIT) no process
Last message: {:EXIT, #PID<0.71.0>, {:noproc, {:gen_fsm, :sync_send_all_state_event, [#PID<0.321.0>, {:new_stream, #PID<0.71.0>}]}}}
State: {:state, {:local, GRPC.Adapter.Cowboy.ServerSup}, :one_for_one, [], :undefined, 1, 5, [], 0, GRPC.Adapter.Cowboy.ServerSup, []}

**Comment by tony612** [comment]
Yes. Chatterbox will disconnect when being inactive for a while. I'll fix this later.

**Comment by tony612** [comment]
It's fixed on master. Please update `grpc` and `cowboy`
