### ISSUE TITLE
Unexpected RECV_DATA message when making unary RPCs

### ISSUE THREAD

**Issue by simon-shopify** [tony612/grpc-elixir#43]
I was making unary RPCs and I noticed unwanted RECV_DATA messages. I was able to reproduce the issue with the [`route_guide`](https://github.com/tony612/grpc-elixir/tree/f3cd74e63e575ae6a96284fbbc686a8fb2d3b942/examples/route_guide) example. I added the following code the display these messages at the end of [`client.exs`](https://github.com/tony612/grpc-elixir/blob/f3cd74e63e575ae6a96284fbbc686a8fb2d3b942/examples/route_guide/priv/client.exs)
```elixir
defmodule Flush do
  def flush() do
    receive do
      message ->
        IO.inspect(message, [binaries: :as_strings]))
        flush()
    after
      0 -> :ok
    end
  end
end

Flush.flush()
```

I see messages like
```
{:RECV_DATA, 1,
 "\0\0\0\0O\n:Berkshire Valley Management Area Trail, Jefferson, NJ, USA\x12\x11\b\x9A\xA6\x8C\xC3\x01\x10\x96\x9F\x98\x9C\xFD\xFF\xFF\xFF\xFF\x01"}
```
which is the whole response as far as I can tell.

I do not see such messages when I comment out the unary calls to keep only the streaming calls. I guess the former does not consume them, which does not seem to be on purpose.

**Comment by tony612** [comment]
You can try `add-gun` branch, which uses gun as the default adapter and should fix this problem.

**Comment by tony612** [comment]
Now it's on hex 🎉 https://hex.pm/packages/grpc
