### ISSUE TITLE
Is Context / metadata supported?

### ISSUE THREAD

**Issue by bjuretic** [tony612/grpc-elixir#44]
Hi,

do you support a Context (metadata passing from the client) in the server and the server interceptors? I mean something like the example in Java which is using Context to perform JWT authentication:
https://github.com/saturnism/grpc-java-by-example/tree/master/metadata-context-example/src/main/java/com/example/grpc

**Comment by tony612** [comment]
Not now. But it's in the plan.

**Comment by tony612** [comment]
I've implemented this in `next` branch. You can try it. And `interop/lib/interop/client.ex` and `interop/lib/interop/server.ex` can be good examples for this.

**Comment by tony612** [comment]
Now it's on hex 🎉  https://hex.pm/packages/grpc
