### ISSUE TITLE
grpc requires Cowboy ~> 2.2.0, phoenix requires 1.0

### ISSUE THREAD

**Issue by ospaarmann** [tony612/grpc-elixir#47]
Currently grpc-elixir requires cowboy ~> 2.2.0. When trying to use it inside a phoenix app this causes an issue because phoenix itself requires cowboy ~> 1.0.

```
Failed to use "cowboy" (version 1.1.2) because
  apps/trope_api/mix.exs requires ~> 1.0
  deps/grpc/mix.exs requires ~> 2.2.0
  phoenix (version 1.3.2) requires ~> 1.0
  mix.lock specifies 1.1.2

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

Is Cowboy 2.2.0 really necessary or could you go down with the version in your mix.exs?

**Comment by ospaarmann** [comment]
Nevermind. I just realized you need Cowboy 2. For anyone interested, here is a guide on how to use Cowboy 2 with Phoenix 1.3: https://maartenvanvliet.nl/2017/12/15/upgrading_phoenix_to_http2/

**Comment by tony612** [comment]
Yes, it requires cowboy ~> 2.2.0 :)
