### ISSUE TITLE
Generators, Modules & Typespecs

### ISSUE THREAD

**Issue by hayesgm** [tony612/grpc-elixir#5]
Currently, when you run the generators, you end up with two generated files, which look something like the following:

`my_service.pb.ex`:

```elixir
# DO NOT EDIT!
...
defmodule MyService do
  use Protobuf, """
syntax = "proto3";

service MyService {
  rpc Get (GetRequest) returns (GetReply) {}
}

message GetRequest {
  string name = 1;
  int32 age = 2;
}

message GetReply {
  string hello_name = 1;
}
"""
end
```

and

```elixir
defmodule MyService.MyService.Server do
  use GRPC.Server, service: MyService.MyService.Service
  def get(get_request, _stream) do
  end
end
```

Getting dropped in there after creating a new project, it's incredibly difficult to move forward since you don't know what your types are from the protobufs and you don't have a typespec to guide you (or dialyzer) in your service definitions. I think it would be **incredibly** beneficial to someone building a service on grpc-elixir to have generators that instead create:

`my_service.pb.ex`:

```elixir
# DO NOT EDIT!

defmodule MyService do
  defmodule GetRequest do
    @type t :: %{
        name: String.t,
        age: integer()
    }
    defstruct [name: "", age: 0]
  end

  defmodule GetReply do
    @type t :: %{
      hello_name: String.t
    }
    defstruct [name: ""]
  end
end
```

`my_service_server.ex`

```elixir
defmodule ManifestService.ManifestService.Server do
  @spec(MyService.GetRequest.t, GRPC.Server.Stream.t) :: MyService.GetReply.t | nil
  def get(get_request, _stream) do
  end
end
```

with the protobufs modules generated a priori, it becomes very to look up what the definition of the modules are in your server code. Additionally, it is trivial to write them into the server with the clear function specs and becomes easy to dialyze your code.

I wanted to garner feedback from @tony612 if this is something interesting and important to this project?

**Comment by tony612** [comment]
This is a very interesting idea. But for the service definition part, maybe it's better to implement this feature in [exprotobuf](https://github.com/bitwalker/exprotobuf)? This feature is not very important right now because I have to finish some basic features first, but I'll put this on my TODO list. Thank you! 👍🏼

**Comment by tony612** [comment]
btw, you can try to implement this feature if you have time. I'm happy to accept PR for it.😁

**Comment by hayesgm** [comment]
Cool, I'll continue looking into this.

**Comment by tony612** [comment]
This has been supported in the new protobuf lib https://github.com/tony612/protobuf-elixir

**Comment by hayesgm** [comment]
That's really cool. Great work spending the time to build that library!
