### ISSUE TITLE
Plans to put this repository on official gRPC website

### ISSUE THREAD

**Issue by chintan-mishra** [tony612/grpc-elixir#57]
Pros:
1. It'd bring this project in limelight.
2. Drive developers to contribute and use this lib.
3. Elixir will get some attention from dev community

Cons:
`<need help, can't think of anything>`

**Comment by chintan-mishra** [comment]
@tony612 I noticed that you closed this issue. I was hoping to find reference to this repository on https://grpc.io but couldn't. Can you shed some light on this?

**Comment by tony612** [comment]
@chintan-mishra There're only official implementations in the website. Will add Elixir when they have something like https://github.com/protocolbuffers/protobuf/blob/master/docs/third_party.md.

**Comment by chintan-mishra** [comment]
@tony612 Okay. Thank you.

**Comment by tony612** [comment]
btw, you can find Elixir implementation here https://github.com/grpc-ecosystem/awesome-grpc#elixir
