### ISSUE TITLE
Using Google.Protobuf predefined types (e.g. Empty)

### ISSUE THREAD

**Issue by pnowosie** [tony612/grpc-elixir#63]
Hey @tony612 
Kudos for your great work with protobufs and gRPC.

I'm extending HelloWorld example trying to create method which does not expect request param.
In proto definition file I imported `import "google/protobuf/empty.proto";` and use it in rpc definition, e.g. `rpc HeartBeat (google.protobuf.Empty) returns (HelloReply) {}` 

Then I regenerated the code with provided `protoc` command. So far everything went smooth.

Then following example in `iex` REPL I created channel, but I don't know how to pass `Google.Protobuf.Empty` message to the stub's method.
Does elixir-protobuf lib provides predefined types from Google's protoc includes?

Thank you for help!

**Comment by tony612** [comment]
Thank you.

I think you can use this package https://github.com/tony612/google-protos

**Comment by pnowosie** [comment]
Works perfectly well, 🥇 Thanks @tony612.
✅ Closing issue.

As a reference for inexperience Elixir users (which I am), here is what I did:
 * In [mix.exs](https://github.com/tony612/grpc-elixir/blob/master/examples/helloworld/mix.exs) I've added dips: `{:google_protos, git: "https://github.com/tony612/google-protos", tag: "v0.1.0"},`
 * Get dips & recompile `mix do dips.get, compile`
 * Call heart_beat method from code:
```elixir
channel |> Helloworld.Greeter.Stub.heart_beat(Google.Protobuf.Empty.new())
```
