### ISSUE TITLE
Sending 0 with grpc python results in "nil"

### ISSUE THREAD

**Issue by AleksandarFilipov** [tony612/grpc-elixir#64]
Thanks for a great library, i have issues accessing vi python,
given the following proto file

```
syntax = "proto3";

// fix this with compiler flag -I

option java_multiple_files = true;
option java_package = "io.grpc.nilapi";
option java_outer_classname = "NilTest";
option objc_class_prefix = "CORE";

package nilapi;

service IntegerService {
  rpc SendInteger (SenderInfo) returns (SenderInfo) {}
}

message SenderInfo {
  int32 frequency = 3;
}
```

and the following python client
```python
channel = grpc.insecure_channel('localhost:50051')
    stub = nil_test_pb2_grpc.IntegerServiceStub(channel)
    send_int = nil_test_pb2.SenderInfo(frequency=0)
    a = stub.SendInteger(send_int)
    print("Expecting an int back %d", a)

```

1. the input recieved on the elixir side reports that the frequency is nil (and not 0 as expected)

2. The problem is reversible, if elixir returns the returned value will be null.

elixir code:

```elixir
defmodule Nilapi.IntegerService.Server do
  use GRPC.Server, service: Nilapi.IntegerService.Service
  require Logger
  alias GRPC.Server

  @spec send_integer(Nilapi.SenderInfo.t, GRPC.Server.Stream.t) :: Nilapi.SenderInfo.t
  def send_integer(request, _stream) do
    Logger.debug inspect request
    Nilapi.SenderInfo.new(frequency: 0)
  end  
end
```

All the code for reproducing is attached.

[grpc_python_nil.zip](https://github.com/tony612/grpc-elixir/files/2072096/grpc_python_nil.zip)

**Comment by tony612** [comment]
Thank you!

It's not a bug. In proto3, all fields have default values and we can tell if it's set. See https://developers.google.com/protocol-buffers/docs/proto3#default for more detail
> Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all: you should bear this in mind when defining your message types.

**Comment by tony612** [comment]
Wait. You said the `request` you got on Elixir side(server) is `%Nilapi.SenderInfo{frequency: nil}`?

**Comment by tony612** [comment]
What I got is right:
```
# elixir
23:58:19.203 [debug] %Nilapi.SenderInfo{frequency: 0}

# python
# I change last code to `print("Expecting an int back ", a.frequency)`
Expecting an int back  0
```

**Comment by tony612** [comment]
Can you describe what you expect? Maybe you can paste your input and output messages you expect. I guess it's
```
# send from Python
nil_test_pb2.SenderInfo(frequency=0) # frequency is 0

# received in Elixir
%Nilapi.SenderInfo{frequency: 0} # frequency is 0
```

So, it's same with my test. The log I got on Elixir side is
```
# elixir
23:58:19.203 [debug] %Nilapi.SenderInfo{frequency: 0}
```

I didn't see where's the nil.

**Comment by tony612** [comment]
What‘s your grpc-elixir & protobuf-elixir version? Maybe you can try
upgrade them.

**Comment by AleksandarFilipov** [comment]
Here we go again :)

if i do
```python
def run():
    channel = grpc.insecure_channel('localhost:50051')
    stub = nil_test_pb2_grpc.IntegerServiceStub(channel)
    send_int = nil_test_pb2.SenderInfo(frequency=0)
    a = stub.SendInteger(send_int)
    print("Expecting an int back %d", a.frequency)
    # set_fan_speed(stub, 8, 0)
```
python reports - as expected
```
Expecting an int back %d 0
```

elixir reports - _not_ as expected
```elixir
21:26:18.133 [debug] %Nilapi.SenderInfo{frequency: nil}
```
i use the following version - as far as i can tell latest and greatest.

```
  "protobuf": {:hex, :protobuf, "0.5.4", "2e1b8eec211aff034ad8a14e3674220b0158bfb9a3c7128ac9d2a1ed1b3724d3", [:mix], []},
  "grpc": {:git, "https://github.com/tony612/grpc-elixir.git", "9e13fda84971e8957bcdd11b8ba8de4c9c29829b", []},
```

Whats going on here?

if i replace the 0 with a 1 it all works as expected.

python versions:
```
grpcio==1.12.0
grpcio-tools==1.12.0
afilipov@got12045jymc2 ~/compentence/grpc_python (afilipov/report_nil_bug) $ pip freeze | grep proto
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
protobuf==3.5.2.post1
```

So confusing.

**Comment by tony612** [comment]
@AleksandarFilipov Are you using proto2 in the Elixir side?

**Comment by AleksandarFilipov** [comment]
Hi again Tony, thanks for helping me out.

protoc --version
libprotoc 3.4.0

not sure how to check version of protoc-gen-elixir
``` 
protoc -I ./proto_files/  --elixir_out=plugins=grpc:./lib/proto_files ./proto_files/*.proto
```

Generated code on elixir side:
```elixir
defmodule Nilapi.SenderInfo do
  use Protobuf

  @type t :: %__MODULE__{
    frequency: integer
  }
  defstruct [:frequency]

  field :frequency, 3, optional: true, type: :int32
end

defmodule Nilapi.IntegerService.Service do
  use GRPC.Service, name: "nilapi.IntegerService"

  rpc :SendInteger, Nilapi.SenderInfo, Nilapi.SenderInfo
end

defmodule Nilapi.IntegerService.Stub do
  use GRPC.Stub, service: Nilapi.IntegerService.Service
end

```

whats next....

**Comment by tony612** [comment]
@AleksandarFilipov I see. I think it's because you're using an old version protoc-gen-elixir. You can install the latest version directly:
```
mix escript.install hex protobuf
# or from github(master)
mix escript.install github tony612/protobuf-elixir
```

**Comment by AleksandarFilipov** [comment]
YES now it works. Many thanks for your help and your commitment. Keep up the excellent work!
