### ISSUE TITLE
Timeline for stable hex release

### ISSUE THREAD

**Issue by ospaarmann** [tony612/grpc-elixir#65]
Hey,

I am really looking forward to a stable release on hex since a project of mine depends on grpc-elixir. I cannot move forward without stable dependencies.

As I understand an issue was that gun wasn't stable. This seems to have changed yesterday (I discovered it by accident, no worries): https://github.com/ninenines/gun/releases

Is there a timeline on a stable release? Is there something we can help with? 

❤️

**Comment by tony612** [comment]
But actually, gun is not released on hex 😂

**Comment by ospaarmann** [comment]
Well, maybe this can be changed 😉. If you need support with anything, let me know!

**Comment by bendiken** [comment]
> But actually, gun is not released on hex 😂

That problem has been sorted in the past months: https://hex.pm/packages/gun

@tony612 Would it be possible to go ahead and release 0.3.0 on Hex.pm?

**Comment by bendiken** [comment]
Something to note: #77 means that the `gun` dependency should probably be locked to `~> 1.2.0` for now.

**Comment by tony612** [comment]
0.3.1 was released https://hex.pm/packages/grpc
