### ISSUE TITLE
Error compiling hpack

### ISSUE THREAD

**Issue by baldmountain** [tony612/grpc-elixir#7]
Hi,

Just made a quick project to try this against an existing service. I followed the instructions in the README and ran into a problem compiling hpack using mix do deps.get, compile.

```bash
===> Compiling hpack
===> Compiling src/huffman.erl failed
src/huffman.erl:none: undefined parse transform 'lager_transform'
```

Did I miss a step?

**Comment by tony612** [comment]
It seems some changes in hpack today have problems. I'll look into this later. But here is a quick fix: change hpack dep line in `mix.exs` to `{:hpack, github: "joedevivo/hpack", ref: "d903a08", override: true}`

**Comment by tony612** [comment]
But I tried with master of hpack. It works. Try this `mix do deps.clean hpack, deps.get`?

**Comment by baldmountain** [comment]
I tried `mix do deps.clean hpack, deps.get` and still get the same error compiling hpack. I added the hpack ref: dependency and the compile gets farther but stops with the same issue in goldrush. :(

It's not an important issue at the moment. I was just giving something a try. Feel free to ignore this issue if it is a distraction.

**Comment by tony612** [comment]
@baldmountain Could you paste your hpack line in the `mix.lock` file and the result of `cat deps/hpack/.git/HEAD`(actual Ref of hpack)?

**Comment by baldmountain** [comment]
I didn't add hpack as a dependency. Here's my entire mix.exs file:

```elixir
defmodule Sabre.Mixfile do
  use Mix.Project

  def project do
    [app: :sabre,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger, :grpc]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [{:grpc, github: "tony612/grpc-elixir"}]
  end
end
```

`cat deps/hpack/.git/HEAD` = `6b58b6231e9b6ab83096715120578976f72f4f7c`

All I did for this is `mix new sabre --module Sabre`, add the grpc dependency, and run `mix do deps.get, compile` as the README says.

**Comment by baldmountain** [comment]
Oh , the hpack line in mix.lock:

```
  "hpack": {:git, "git://github.com/joedevivo/hpack.git", "6b58b6231e9b6ab83096715120578976f72f4f7c", [branch: "master"]},
```

**Comment by tony612** [comment]
@baldmountain  It seems related to a possible bug in Elixir 1.4. I saw an issue here https://github.com/elixir-lang/elixir/issues/5640 and the topic here https://elixirforum.com/t/undefined-parse-transform-lager-transform-with-elixir-1-4-0/3143

**Comment by tony612** [comment]
Please upgrade Elixir to 1.4.1, which fixes this problem https://github.com/elixir-lang/elixir/releases/tag/v1.4.1
