### ISSUE TITLE
How to handle client streams on server-side?

### ISSUE THREAD

**Issue by fschuindt** [tony612/grpc-elixir#70]
**Edit note:** _This issue was described in other way. I made some changes to the code that allows me to bring a more complete question, here it goes:_

Given the following proto:
```proto
syntax = "proto3";

package Streamer;

service Broadcast {
  rpc Broadcast (stream Video) returns (BroadcastResponse) {}
}

service Tune {
  rpc Tune (TuneRequest) returns (stream Video) {}
}

message Band {
  string uid = 1;
  string key = 2;
}

message TuneRequest {
  Band band = 1;
}

message Video {
  string index = 1;
  bytes chunk = 2;
}

message BroadcastResponse {
  bool success = 1;
  Band band = 2;
}
```

I'm having trouble in implementing the `Broadcast` server in Elixir.

Here is my current implementation:
```elixir
defmodule Streamer.Servers.Broadcast do
  require Logger

  use GRPC.Server, service: Streamer.Broadcast.Service

  alias Streamer, as: S

  def broadcast(request, _stream) do
    do_broadcast(request, null_band())
  end

  defp do_broadcast(request, band) do
    Logger.info "Started broadcast | Band UID: #{band.uid} | Band Key: #{band.key}"

    Enum.map(request, &(handle/1))

    S.BroadcastResponse.new(success: true, band: band)
  end

  defp handle(video) do
    IO.puts "Gathered -> index: #{video.index}, chunk: #{video.chunk}"
  end

  defp null_band do
    S.Band.new(uid: "000", key: "111")
  end
end
```

And to make things clear, here's my Ruby client:
```ruby
module SyrinxClient
  class Broadcast
    def initialize
      @stub = Streamer::Broadcast::Stub
                .new('localhost:7171', :this_channel_is_insecure)
    end

    def perform
      reqs = RandomVideo.new
      resp = @stub.broadcast(reqs.each)
      p "response: #{resp.inspect}"
    end
  end

  class RandomVideo
    def initialize; end

    def each
      return enum_for(:each) unless block_given?
      loop do
        v = video
        p v.inspect
        yield v
      end
    end

    private

    def video
      Streamer::Video.new(
        index: rand(0..255).to_s,
        chunk: SecureRandom.uuid
      )
    end
  end
end
```

Notice the `loop do` line in my Ruby client. I'm just streaming random data in a loop. And here begins my problem.

When I run this, my Elixir server just prints the "Started broadcast ..." message and then it stands still. I was expecting it to keep printing the "Gathered -> index: ..." message as long as it receives. Sometimes it prints some of those "Gathered" messages, but just a few like four, two, one. Then it seems to stop.

But look at this part of the Ruby client:
```ruby
      loop do
        v = video
        p v.inspect
        yield v
      end
```

If I change it to:
```ruby
      10_000.times do
        v = video
        p v.inspect
        yield v
      end
```

Effectively killing the infinite loop. By doing this it seems to work just fine. But there's a catch: It seems to print all the "Gathered" messages at the end of the stream. Not as long as it receives it. Which is what I was expecting.

So looks like it waits the stream to end to start doing the work, but:

Another fact is that by adding a `sleep` in the Ruby client like so:
```ruby
      loop do
        p video.inspect
        yield video
        sleep rand(1..2)
      end
```
But keeping it infinite with `loop do`, it also seems to work just fine. And this time even better 'cause it now seems to be in sync. Pack sent, pack processed at the same time.

My question is: Is there a way to handle a "infinite" stream asynchronously? Eg.: It keeps processing new packs as long as it receives with no forced delay by the client?

Thank you!

**Comment by fschuindt** [comment]
Well, apparently my client was sending data too fast.(?)

That's my server:
```elixir
  defp do_broadcast(request, band) do
    Logger.info "Started broadcast | Band UID: #{band.uid} | Band Key: #{band.key}"

    Enum.map(request, &(handle(&1)))
  end
```
I've changed my client code in Ruby too. All I did was to set a random sleep between 1 and 2 seconds for each pack sent in the client. And now it seems to work.

Can't I send a "fast as it can get" packs during stream?

**Comment by fschuindt** [comment]
BTW, I'm still interested in any kind of guidance throughout this issue here. :)

**Comment by tony612** [comment]
OK. I can reproduce the problem now. Let me try to fix it. Thank you.

**Comment by tony612** [comment]
@fschuindt Could you try the master branch?

**Comment by fschuindt** [comment]
@tony612 Hi there, thank you for having time to look at it.

Changed it to use the master branch here and now it fails with:
```
20:43:48.728 [error] Ranch listener "Streamer.Servers.Broadcast,Streamer.Servers.Tune" had connection process started with :cowboy_clear:start_link/4 at #PID<0.236.0> exit with reason: {:badarg, [{:erlang, :cancel_timer, [:undefined, [async: true, info: false]], []}, {:cowboy_http2, :frame, 2, [file: '/home/fschuindt/apps/mine/project_july/syrinx/deps/cowboy/src/cowboy_http2.erl', line: 483]}, {:cowboy_http2, :parse, 2, [file: '/home/fschuindt/apps/mine/project_july/syrinx/deps/cowboy/src/cowboy_http2.erl', line: 343]}, {:cowboy_http, :parse, 2, [file: '/home/fschuindt/apps/mine/project_july/syrinx/deps/cowboy/src/cowboy_http.erl', line: 253]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```
Sometimes it prints the `[info]  Started broadcast | Band UID: 000 | Band Key: 111` message, but is not consistent.

I remember seeing this error before, that was why I was using the `0.3.0-alpha.2` Hex package version instead of the `master` one, I'm sorry I didn't mentioned it before.

But in order to provide you a richer background, I have set up this repository:
- [https://github.com/fschuindt/project_july](https://github.com/fschuindt/project_july)

It can guide you:
- `broadcaster`: A Rust application, you can ignore that.
- `proto`:  My Protobuf file and its "compilation" to some languages.
- `ruby_client`: The proper Ruby client.
- `rust_proto_builder`: A small Rust program to create my Rust files from the Protobuf ones, you can also ignore that.
- `syrinx`: A Mix Umbrella app with just one app. This app is the Elixir gRPC server itself.

## The Ruby Client
Inside the project directory, you can run:
```
$ bundle install
```

Then:
```
$ ruby client.rb --broadcast
```

or:
```
$ ruby client.rb --tune
```

You can also ignore the `--tune` option, the client is messed with it at the moment. And our focus here is the `--broadcast` one. Which will fire the `ruby_client/broadcast.rb` client and the `syrinx/apps/streamer/lib/servers/broadcast.ex` server.

## The Elixir Server
Notice that the `project_july` repository uses the grpc-elixir `0.3.0-alpha.2` Hex package at the master branch. But there's a branch named `grpc-elixir/master` that uses the grpc-elixir master release as package. So you can switch branches to checkout behaviors.

So the main idea is to start the `syrinx` application with `$ iex -S mix` (inside the `/syrinx`dir) and then call the `$ ruby client --broadcast` (inside the `/ruby_client`dir) to see how it goes.

Let me know if any further information is needed.

Thanks!

**Comment by tony612** [comment]
@fschuindt This error is related to a cowboy's bug which I fixed in this PR https://github.com/ninenines/cowboy/pull/1304 (but not merged yet)

**Comment by fschuindt** [comment]
@tony612 Superb! Thank you a lot. My so called broadcast server is working like a charm.

BTW, two other strange facts are happening, now regarding the tune server:
- 1. My tune server seems to get out of sync with my tune client.
- 2. When I close (Ctrl + C) the Ruby tune client, the Elixir tune server keeps on sending replies for ever. I know I've defined a non-stoppable recursion loop. My question is: How can I stop the loop when the connection stops?

Let me explain. But also notice I have updated the `project_july` repository with all files from my current state.

#### i. *My tune server seems to get out of sync with my tune client.*
When I start the tune client pointing to server it all starts good. But after a few seconds later (may be 30 seconds later) the packets get out of sync. The server is sending packages way ahead from the client position.

I let the packages to have a integer index so I can monitor the synchronization, after some seconds the server is saying:
```
23:31:53.693 [info]  Replied -> index: 1604120, chunk: 2badba37-6b12-4ad1-a4bf-9a52a9a4e
```

And at the same time the client is showing:
```
<Streamer::Video: index: "842433", chunk: "c3994c3b-d9cc-47a0-b7e3-67a206486c7b">
```

As you can see, the server is at the index 1604120, while the client is at 842433. The server gets way ahead over time.

#### i. *When I close (Ctrl + C) the Ruby tune client, the Elixir tune server keeps on sending replies [...]*
Having my tune server described as:
```elixir
defmodule Streamer.Servers.Tune do
  require Logger

  use GRPC.Server, service: Streamer.Tune.Service

  alias Streamer, as: S

  def tune(request, stream) do
    Logger.info "Started tunning | Band UID: #{request.band.uid} | Band Key: #{request.band.key}"

    do_tune(stream, 1)
  end

  defp do_tune(stream, index) do
    video = random_video(index)
    GRPC.Server.send_reply(stream, video)
    Logger.info "Replied -> index: #{index}, chunk: #{video.chunk}"

    do_tune(stream, index + 1)
  end

  defp random_video(index) do
    S.Video.new(
      index: Integer.to_string(index),
      chunk: random_chunk())
  end

  defp random_chunk do
    SecureRandom.uuid
  end
end
```

You can notice I'm performing a infinite recursion loop. So even after the client stopped running, the server keeps printing out ` [info]  Replied -> [...]` log messages, for ever.

There's a way to know when the client connection closes so I can stop my loop?

I believe that's it.
And again, thank you for everything! :)

**Comment by tony612** [comment]
It's a interesting problem :) I'll look into it these days.

**Comment by tony612** [comment]
Fixed on master.

**Comment by fschuindt** [comment]
@tony612 I don't want to bother you, but I just downloaded the new `grpc-elixir` from GitHub master, recompiled my application and performed the tests again. Both the two issues I reported in my last comment persists. The server gets ahead over time and the server keeps running even after closed connection.

Am I doing something wrong?

**Comment by tony612** [comment]
@fschuindt I tried with your example, it should works. Can you make sure `mix.lock` has changes like this?
```diff
-  "grpc": {:git, "https://github.com/tony612/grpc-elixir.git", "01b815ee3ff11fe761f94cc4361ef861b0b12f0d", [branch: "master"]},
+  "grpc": {:git, "https://github.com/tony612/grpc-elixir.git", "8773a5707532ed5ee2973a6348c2b07aa55733bd", [branch: "master"]},
```
And you can try recompiling deps(with `mix deps.compile grpc`).

**Comment by fschuindt** [comment]
@tony612 Hey! I'm sorry my late response, tight week schedule at my daytime job this week.

And yes! You were right, somehow even after removing the `_build` and `deps` folders, running `mix deps.get` and `mix compile` it wasn't changing the `mix.lock` file at all. So I removed it myself and ran everything again, so the `mix.lock` file got updated and now matches with your last master commit. Great.

I made some extensive tests and more changes to the `project_july` repository and now it's working flawless. At least the Tune service. The biggest change I made was to no longer use the Elixir `:logger` OTP app. Instead I implemented my own crude logger, which uses `IO.puts/1` to print out messages.

The issue with the standard logger is that it was adding a huge bottleneck to the stream and its printing queue was getting full and failing due to the amount of messages sent and the interval between'em.

So as I said, the Tune service is working great. Thank you a lot and congratulations for all your work! :tada: 

But now the Broadcast service concerns me.  
Can you try it yourself? Just take a quick look and you will notice:

*At the `syrinx` folder.*
```
$ iex -S mix
```

*At the `ruby_client` folder.*
```
$ ruby client.rb --broadcast
```

I did noticed some things:
- The client is way faster than the server. It's sending packages so fast that it gets ahead really quick. Sometimes the client stops and waits to the server catch up so it can keep on. But it always get way ahead.
- At some point it crashes without apparent reason. If you let it running, it will probably crash in less than one minute.

Any thoughts?

And again, thank you.

**Comment by fschuindt** [comment]
BTW, I forgot to mention: When I close the Tune client, the server loop now stops successfully. Thank you!

**Comment by fschuindt** [comment]
@tony612 Would be nice to know your thoughts on my last comments before you closing it.

**Comment by tony612** [comment]
@fschuindt Sorry, I thought there's no problem any more. I ran the demo, but didn't see obvious lag between Elixir server and Ruby client. The log they print are very close. This is a screenshot after they ran after 8 minutes from 2018-12-20 06:53:03, then I kill them by hand.
```
ruby client.rb --broadcast
INFO [2018-12-20 06:53:03]: index: 1, chunk: 19178838-ec55-4caa-beae-d9c249bd42c1
INFO [2018-12-20 06:53:03]: index: 2, chunk: 02bf8cc0-d3ef-4736-abcf-dbda90167749
INFO [2018-12-20 06:53:03]: index: 3, chunk: db1ea6c8-3ee1-485d-989f-3a234be526a9
```
![screen shot 2018-12-20 at 3 01 14 pm](https://user-images.githubusercontent.com/1253659/50269256-b289dc80-0468-11e9-8234-e086bb3fb232.png)
