### ISSUE TITLE
Server healthchecking support

### ISSUE THREAD

**Issue by milica-nerlovic** [tony612/grpc-elixir#73]
Hi, @tony612!
My coworkers and I have been trying to include a simple health check for our GRPC servers in our projects, based on the [grpc health checking guide](https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

Ideally, we would want a small library that can be included in projects easily, like:
https://github.com/renderedtext/grpc_health_check/tree/mn/standalone-application

However, when I try including such a library in a [sample project](https://github.com/milica-nerlovic/hello_elixir), the project cannot be compiled. It's own `GRPC.Server.Supervisor` refuses to start:

![screenshot 2018-08-01 10 53 16](https://user-images.githubusercontent.com/21684087/43512006-3ae4c094-957a-11e8-8bd5-4e2cac827acd.png)

At a first glance, it seems like there ca be only one `GRPC.Server.Supervisor` process started.

Any thoughts? 🙂 

The official libraries for supported languages come with the Health Check service already bundled. Have you thought of perhaps adding support for this in `grpc-elixir` directly?

**Comment by tony612** [comment]
Yes, I think so. You can add `GrpcHealthCheck.Server` to your own app like
```
supervisor(GRPC.Server.Supervisor, [{[GrpcHealthCheck.Server, ...others], 50051}])
```
 Hmm.. I think I can add health check later.

**Comment by milica-nerlovic** [comment]
Yes, this is the exact solution we opted for in our apps as well. 🙂 

Thanks for replying, @tony612. 👍
