### ISSUE TITLE
interop tests fail with gun 1.3.0

### ISSUE THREAD

**Issue by JayH5** [tony612/grpc-elixir#77]
As of c0eaa61d789f5c5b9e3c2f4c213944bebaf2c72c, when using gun 1.3.0, the interop tests fail with an error like:
```
...
Round 8
Run empty_unary!
Run large_unary!
Run client_streaming!
Run server_streaming!
Run ping_pong!
Run empty_stream!
** (MatchError) no match of right hand side value: {:error, %GRPC.RPCError{message: "{:connection_error, :flow_control_error, :\"The flow control window must not be greater than 2^31-1. (RFC7540 6.9.1)\"}", status: 2}}
    (interop) lib/interop/client.ex:85: Interop.Client.empty_stream!/1
    script/run.exs:18: anonymous fn/2 in :elixir_compiler_1.__FILE__/1
    (elixir) lib/enum.ex:771: anonymous fn/3 in Enum.each/2
    (elixir) lib/enum.ex:2967: Enum.reduce_range_inc/4
    (elixir) lib/enum.ex:1930: Enum.each/2
    script/run.exs:41: (file)
```

The tests seem to fail in an inconsistent point, usually after around 8-9 rounds of the test.

With gun 1.2.0 and below, the tests pass. I'm not sure exactly what has changed in gun to cause this but am making this issue to record the problem.

**Comment by heath** [comment]
FWIW, I haven't been able to replicate this issue on 936f5362bb1f16e671d368605f0195328d16e441 with gun 1.3.0.

**Comment by tony612** [comment]
fixed by https://github.com/tony612/grpc-elixir/commit/e5ecebcb811fd62025201b322ae671b67042fe28
