### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by arnaud-lb** [tony612/grpc-elixir#8]
This package doesn't seem to support files that have import statements. Is there a way to use such files currently ?

exprotobuf seems to support import statements when providing all the imported files explicitly, however I can't find a way to do that with grpc-elixir.

**Comment by tony612** [comment]
It's indeed an issue. I'm trying to support this recently. exprotobuf and gpb support import, but some work is still needed to integrate with gRPC.

**Comment by tony612** [comment]
Some thoughts about this feature: The current implement(mix task) and protoc-erl(what gpb implements) may be wrong. The right solution should be writing a plugin for the official `protoc` as [here](https://developers.google.com/protocol-buffers/docs/reference/other?csw=1) mentions(though the doc is doesn't provide details about writing a plugin).

**Comment by alexander-alvarez** [comment]
it's defined here:
> A plugin is just a program which reads a CodeGeneratorRequest protocol buffer from standard input and then writes a CodeGeneratorResponse protocol buffer to standard output.

and the definition for those are given here:
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.plugin.pb

I might take a stab at it when cycles free up

**Comment by tony612** [comment]
@alexander-alvarez Thank you. I already found it last month. btw, I'm trying to implement that by Elixir recently, but it will take some time 😀

**Comment by alexander-alvarez** [comment]
@tony612  you doing it as a separate application?

**Comment by tony612** [comment]
@alexander-alvarez I'm trying to create a plugin for protoc to generate the Elixir code from the proto file.

**Comment by tony612** [comment]
exprotobuf is replaced by [protobuf](https://github.com/tony612/protobuf-elixir) now. So import has been supported. Doc is coming :)
