### ISSUE TITLE
Exception handler middleware

### ISSUE THREAD

**Issue by shiroyasha** [tony612/grpc-elixir#84]
I am looking into ways to set up a exception handlers for a GRPC service.

For example, with Sentry currently do:

``` elixir
defmodule HelloWorldService do
  use GRPC.Service
  
  def say_hello(req, call) do
    capture_exceptions(fn ->
      1 / 0
    end)
  end

  defp capture_exception(fun) do
     fun.()
   rescue
     e ->
       stacktrace = __STACKTRACE__
 
       Sentry.capture_exception(e, stacktrace: stacktrace)
 
       Kernel.reraise(e)
   catch
     kind, reason ->
       stacktrace = __STACKTRACE__
       exception = Exception.normalize(kind, reason, stacktrace)
 
       Sentry.capture_exception(
         exception,
         stacktrace: stacktrace,
         error_type: kind
       )
 
       :erlang.raise(kind, reason, stacktrace)
   end
end
```

Ideally, I would like to set up something like a middleware if possible:

``` elixir
defmodule HelloWorldService do
  use GRPC.Service
  use Sentry.GRPC

  def say_hello(req, call) do
    1 / 0
  end
end
```

Any tips on how we could achieve this?

**Comment by shiroyasha** [comment]
I ended up using `__before_compile__` and dynamically redefined rpc functions.

https://github.com/renderedtext/sentry_grpc/blob/master/lib/sentry_grpc.ex#L27

**Comment by tony612** [comment]
Maybe you can try the new interceptor feature. See https://github.com/tony612/elixir-grpc-prometheus as a reference. Not sure if there's problem with interceptors. Please give suggestion :)

btw, here's the PR https://github.com/tony612/grpc-elixir/pull/62

**Comment by shiroyasha** [comment]
I too thought of interceptors first before implementing the previous code. I copied the logger example and tweaked it with the attempt to collect errors.

Unfortunately, the `next()` function returns an `{:error, %GRPC.RPCError{} = error}` tuple that already handled errors and exceptions.

@tony612 is there a way to access the raw error/exception in the interceptors?

---

On the sidenote: The new interceptors are very cool, especially the Prometheus one. Nice work 👏.

**Comment by shiroyasha** [comment]
I'll close the issue. We are so far happy with https://github.com/renderedtext/sentry_grpc.
