### ISSUE TITLE
Receive "upstream connect error or disconnect/reset before headers" while using Envoy Proxy

### ISSUE THREAD

**Issue by mmendez512** [tony612/grpc-elixir#86]
Hello,

I'm trying to use GRPC-Web client, which requires an L7 proxy, in this case, Envoy. Refer: https://github.com/grpc/grpc-web

And I followed the Helloworld example that uses Common-JS client and a Node server (https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld), and that works fine through the Envoy proxy. Then I switched out the node server for Elixir GRPC server, called it from my Common-JS client and it didn't work. 

So I tried something else: I started my GRPC server in Elixir (on port 9090) and setup an Elixir client on the port that Envoy listens to (port 8080) and I received this message:

> {:error, %GRPC.RPCError{message: "upstream connect error or disconnect/reset before headers", status: 14}}

NOTE: I've built Envoy from source, instead of running it through Docker. Did this to rule out any container network issues. 

And I'm using this envoy config file and made no changes to it: https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/helloworld/envoy.yaml

FULL STACK TRACE:
> iex -S mix
Erlang/OTP 21 [erts-10.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> GRPC.Server.start(Helloworld.Greeter.Server, 9090)
{:ok, #PID<0.201.0>, 9090}
iex(2)> {:ok, channel} = GRPC.Stub.connect("localhost:8080")
{:ok,
 %GRPC.Channel{
   adapter: GRPC.Adapter.Gun,
   adapter_payload: %{conn_pid: #PID<0.225.0>},
   cred: nil,
   host: "localhost",
   interceptors: [],
   port: 8080,
   scheme: "http"
 }}
iex(3)> request = Helloworld.HelloRequest.new(name: "you")
%Helloworld.HelloRequest{name: "you"}
iex(4)> {:ok, reply} = channel |> Helloworld.Greeter.Stub.say_hello(request)
** (MatchError) no match of right hand side value: {:error, %GRPC.RPCError{message: "upstream connect error or disconnect/reset before headers", status: 14}}
    (stdlib) erl_eval.erl:453: :erl_eval.expr/5
    (iex) lib/iex/evaluator.ex:249: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:229: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:207: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:94: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:24: IEx.Evaluator.init/4

**Comment by tony612** [comment]
Got it. I'll try the demo.

**Comment by mmendez512** [comment]
Thanks.

**Comment by tony612** [comment]
It works for me, actually. I changed cluster's socket address to `host.docker.internal` to fix the network problems. 
![image](https://user-images.githubusercontent.com/1253659/50397898-5bf50900-07ae-11e9-896c-550b6718170d.png)

My code is at https://github.com/tony612/hello-grpc/commit/b97110e76d19e83fc43ccb6d005bf19cc8535bdb

**Comment by mmendez512** [comment]
I don't get it, it still doesn't work for me. :( Even with your updated branch, I'm getting the same issue. Works fine with my node server and I even created a Java server, that works, too.

**Comment by tony612** [comment]
Are you using Docker for Envoy? Or still built by yourself? I just do by the README https://github.com/grpc/grpc-https://github.com/grpc/grpc-web/blob/09604c483732a0cabd93b5658aad0b380ff23a29/net/grpc/gateway/examples/helloworld/README.md#run-the-example , but changing the last line of `net/grpc/gateway/examples/helloworld/envoy.yaml` to
```diff
-    hosts: [{ socket_address: { address: localhost, port_value: 9090 }}]
+    hosts: [{ socket_address: { address: host.docker.internal, port_value: 9090 }}]
```
And then run this docker command:
```
docker run -p 8080:8080 helloworld/envoy # instead of docker run -d -p 8080:8080 --network=host helloworld/envoy
```

**Comment by mmendez512** [comment]
If I recall right, I did both. I'll make sure and do it via Docker again.

**Comment by mmendez512** [comment]
Yeah, it was both. I'm going to close the issue. It worked fine for you, and I'm not going to spend anymore time on this -- decided to not to use GRPC. Thanks for the help.

**Comment by AleksandarFilipov** [comment]
Can confirm than envoy works a expected :+1:  :)
