### ISSUE TITLE
gRPC client got gun's flow control error when sending data over 8M.

### ISSUE THREAD

**Issue by sunboshan** [tony612/grpc-elixir#92]
version

```
  defp deps do
    [
      {:grpc, "~> 0.3.1"},
    ]
  end
```

Repro step

hello.proto

```
syntax = "proto3";

message ReqHello {
  bytes a = 1;
}

message ResHello {
  bytes a = 1;
}

service Hello {
  rpc say_hello(ReqHello) returns (ResHello);
}
```

hello_server.ex
```
defmodule Hello.Server do
  use GRPC.Server, service: Hello.Service

  def say_hello(_req, _stream) do
    ResHello.new(a: "1")
  end
end
```

client.ex
```
defmodule Client do
  def test do
    {:ok, chan} = GRPC.Stub.connect("127.0.0.1:6789")
    Hello.Stub.say_hello(chan, ReqHello.new(a: :crypto.strong_rand_bytes(1024*1024*8)))
  end
end
```

```
$ iex -S mix
iex> Client.test()
{:error,
 %GRPC.RPCError{
   message: "{:connection_error, :flow_control_error, :\"The flow control window must not be greater than 2^31-1. (RFC7540 6.9.1)\"}",
   status: 2
 }}
```

This error is due to gun client got http/2 window update frame too much and it reaches the maximum 2^31 - 1. But I don't know why grpc server would send too many window update frame to gun client. When using only cowboy and gun, it won't have this issue.

**Comment by tony612** [comment]
I guess this issue has been fixed by https://github.com/tony612/grpc-elixir/commit/d07d1357b2c105258f77b908482f694bd11b3c8d

"too many window update frame" is another issue, which affects the performance, but not the reason of this issue.

**Comment by sunboshan** [comment]
Now I know the trick is to send flow update frame with the data size instead of accumulated body size. 

Thanks for fixing! Closing out.
